#!/bin/bash
export CC=gcc-14
export CXX=g++-14
export PATH="/tmp/jf-openjdk-babylon/ccache-bin:/usr/lib/ccache/bin:$PATH"
export USE_CCACHE=1
export CCACHE_EXEC=/usr/bin/ccache
export CCACHE_DIR="/tmp/jf-openjdk-babylon/ccache"
export CCACHE_MAXSIZE=5G
export JAVA_HOME=/usr/lib/jvm/java-26-openjdk
unset _JAVA_OPTIONS

function cleandir() {
  local dir="$1"
  if [ -d "${dir}" ]; then
    echo "Cleaning directory: ${dir}"
    rm -rf "${dir}"
  fi
  mkdir -p "${dir}"
}

cleandir "${CCACHE_DIR}"
cleandir /tmp/jf-openjdk-babylon/ccache-bin

pushd /tmp/jf-openjdk-babylon/ccache-bin || exit 1
paru -Ql gcc gcc14 | awk '/usr\/bin\/./ {print substr($2, 10)}' | xargs -n 1 ln -s /usr/bin/ccache
popd || exit 1

make clean
bash configure \
  --with-stdc++lib=dynamic \
  --with-libjpeg=system \
  --with-giflib=system \
  --with-libpng=system \
  --with-lcms=system \
  --with-zlib=system \
  --with-harfbuzz=system \
  --with-jvm-features=zgc \
  --with-native-debug-symbols=internal \
  --enable-unlimited-crypto \
  --disable-warnings-as-errors \
  --with-vendor-name="JFronny"
make images

_imgdir=build/linux-x86_64-server-release/images

find "${_imgdir}" -iname '*.so' -exec chmod +x {} \;

echo "Build complete. Images are located in ${_imgdir}/jdk"
